### ISSUE TITLE
Initialization crash on Minecraft 1.18.2 with Meteor 0.4.8

### ISSUE THREAD

**Issue by DanielFA88** [MeteorDevelopment/meteor-mbd-addon#5]
Hi, I'm getting this error everytime I try to launch the game:

	at meteordevelopment.addons.mbd.MBDAddon.onInitialize(MBDAddon.java:12)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:97)
	at net.minecraft.class_310.handler$zmf004$onInit(class_310.java:8000)
	at net.minecraft.class_310.<init>(class_310.java:639)

**Comment by DanielFA88** [comment]
I tried also with the newest 0.4.9 and it crashes too... :(
